#!/bin/bash
java -jar ./EventAttendeesHandler/target/EventAttendeesHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.EventAttendeesHandler --java-opts "-Xmx150m"
java -jar ./EventInterestedsHandler/target/EventInterestedsHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.EventInterestedsHandler --java-opts "-Xmx150m"
java -jar ./EventMaybesHandler/target/EventMaybesHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.EventMaybesHandler --java-opts "-Xmx150m"
java -jar ./LikePostsHandler/target/LikePostsHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.LikePostsHandler --java-opts "-Xmx150m"
java -jar ./PostLikesHandler/target/PostLikesHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.PostLikesHandler --java-opts "-Xmx150m"
java -jar ./SharedTableDataInsertionHandler/target/SharedTableDataInsertionHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.SharedTableDataInsertionHandler --java-opts "-Xmx150m"
java -jar ./UserEventsHandler/target/UserEventsHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.UserEventsHandler --java-opts "-Xmx150m"
java -jar ./UserInitHandler/target/UserInitHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.UserInitHandler --java-opts "-Xmx150m"
java -jar ./UserLikesHandler/target/UserLikesHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.UserLikesHandler --java-opts "-Xmx150m"
java -jar ./UserTaggedPlacesHandler/target/UserTaggedPlacesHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.UserTokenHandler --java-opts "-Xmx150m"
java -jar ./UserTokenHandler/target/UserTokenHandler-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.UserTokenHandler --java-opts "-Xmx150m"
java -jar ./Web/target/Web-1.0-SNAPSHOT-fat.jar start -cluster clique.verticles.FacebookAuthenticate --java-opts "-Xmx150m"
